spring:
  profiles:
    active: local
  datasource:
    url: ${RDS_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: mysql

logging.level:
  org.hibernate.SQL: debug
  com.airbnb: debug