spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password:  ${RDS_PASSWORD}

    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  h2:
    console:
      enabled: true
      path: /h2